package com.yuan.www.model;

import java.io.Serializable;
import java.util.Date;

public class Examinations implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.id
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.student_id
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private Integer studentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.score
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.questions
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private String questions;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.answers
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private String answers;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.start_examination_time
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private Date startExaminationTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_examinations.end_examination_time
	 * 
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	private Date endExaminationTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.id
	 * 
	 * @return the value of tb_examinations.id
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.id
	 * 
	 * @param id
	 *            the value for tb_examinations.id
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.student_id
	 * 
	 * @return the value of tb_examinations.student_id
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public Integer getStudentId() {
		return studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.student_id
	 * 
	 * @param studentId
	 *            the value for tb_examinations.student_id
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.score
	 * 
	 * @return the value of tb_examinations.score
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.score
	 * 
	 * @param score
	 *            the value for tb_examinations.score
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.questions
	 * 
	 * @return the value of tb_examinations.questions
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public String getQuestions() {
		return questions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.questions
	 * 
	 * @param questions
	 *            the value for tb_examinations.questions
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setQuestions(String questions) {
		this.questions = questions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.answers
	 * 
	 * @return the value of tb_examinations.answers
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public String getAnswers() {
		return answers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.answers
	 * 
	 * @param answers
	 *            the value for tb_examinations.answers
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setAnswers(String answers) {
		this.answers = answers;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.start_examination_time
	 * 
	 * @return the value of tb_examinations.start_examination_time
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public Date getStartExaminationTime() {
		return startExaminationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.start_examination_time
	 * 
	 * @param startExaminationTime
	 *            the value for tb_examinations.start_examination_time
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setStartExaminationTime(Date startExaminationTime) {
		this.startExaminationTime = startExaminationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_examinations.end_examination_time
	 * 
	 * @return the value of tb_examinations.end_examination_time
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public Date getEndExaminationTime() {
		return endExaminationTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_examinations.end_examination_time
	 * 
	 * @param endExaminationTime
	 *            the value for tb_examinations.end_examination_time
	 * @mbggenerated Mon Sep 25 15:06:37 CST 2017
	 */
	public void setEndExaminationTime(Date endExaminationTime) {
		this.endExaminationTime = endExaminationTime;
	}
}