package com.yuan.www.model;

import java.io.Serializable;
import java.util.Date;

public class Teacher implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer id;

	private String name;

	@Override
	public String toString() {
		return "Teacher [id=" + id + ", name=" + name + ", password="
				+ password + ", position=" + position + ", loginTime="
				+ loginTime + ", tel=" + tel + ", sex=" + sex + ", avater="
				+ avater + ", nationality=" + nationality + ", height="
				+ height + ", weight=" + weight + ", school=" + school + "]";
	}

	private String password;

	private String position;

	private Date loginTime;

	private String tel;

	private String sex;

	private String avater;

	private String nationality;

	private Integer height;

	private Double weight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_teacher.school
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	private String school;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.id
	 * 
	 * @return the value of tb_teacher.id
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.id
	 * 
	 * @param id
	 *            the value for tb_teacher.id
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.name
	 * 
	 * @return the value of tb_teacher.name
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.name
	 * 
	 * @param name
	 *            the value for tb_teacher.name
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.password
	 * 
	 * @return the value of tb_teacher.password
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.password
	 * 
	 * @param password
	 *            the value for tb_teacher.password
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.position
	 * 
	 * @return the value of tb_teacher.position
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.position
	 * 
	 * @param position
	 *            the value for tb_teacher.position
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.login_time
	 * 
	 * @return the value of tb_teacher.login_time
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public Date getLoginTime() {
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.login_time
	 * 
	 * @param loginTime
	 *            the value for tb_teacher.login_time
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.tel
	 * 
	 * @return the value of tb_teacher.tel
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.tel
	 * 
	 * @param tel
	 *            the value for tb_teacher.tel
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.sex
	 * 
	 * @return the value of tb_teacher.sex
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.sex
	 * 
	 * @param sex
	 *            the value for tb_teacher.sex
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.avater
	 * 
	 * @return the value of tb_teacher.avater
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getAvater() {
		return avater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.avater
	 * 
	 * @param avater
	 *            the value for tb_teacher.avater
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setAvater(String avater) {
		this.avater = avater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.nationality
	 * 
	 * @return the value of tb_teacher.nationality
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getNationality() {
		return nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.nationality
	 * 
	 * @param nationality
	 *            the value for tb_teacher.nationality
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.height
	 * 
	 * @return the value of tb_teacher.height
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.height
	 * 
	 * @param height
	 *            the value for tb_teacher.height
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.weight
	 * 
	 * @return the value of tb_teacher.weight
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public Double getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.weight
	 * 
	 * @param weight
	 *            the value for tb_teacher.weight
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setWeight(Double weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tb_teacher.school
	 * 
	 * @return the value of tb_teacher.school
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public String getSchool() {
		return school;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tb_teacher.school
	 * 
	 * @param school
	 *            the value for tb_teacher.school
	 * 
	 * @mbggenerated Sat Sep 02 11:37:10 CST 2017
	 */
	public void setSchool(String school) {
		this.school = school;
	}
}